// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", true);
user_pref("app.normandy.startupRolloutPrefs.browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts", true);
user_pref("app.normandy.user_id", "6252e69f-0cca-4e26-9a79-99361459fb8a");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1547300472);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1547300592);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1546442868);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1547300232);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1547300087);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1547300352);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1547300832);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1547300712);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 450560);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.migration.version", 76);
user_pref("browser.newtabpage.activity-stream.impressionId", "{4922d73c-3ebc-4f52-91cc-e0951efe9e5e}");
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1546383600);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1547299963210");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1547301760210");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1547299964656");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1547303564656");
user_pref("browser.search.region", "FR");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20181209160329");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1547300204");
user_pref("browser.startup.homepage_override.buildID", "20181209160329");
user_pref("browser.startup.homepage_override.mstone", "64.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Yahoo");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "64.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.mint.bookmarksProcessed", true);
user_pref("dom.push.userAgentID", "96eba06086af4908b583225ef114d6e9");
user_pref("extensions.blocklist.lastModified", "Fri, 11 Jan 2019 11:41:17 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.cache.lastUpdate", 1547300474);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20181209160329");
user_pref("extensions.lastAppVersion", "64.0");
user_pref("extensions.lastPlatformVersion", "64.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{32226d24-d94b-491e-980b-83b3e5aeb78e}\",\"addons\":{\"fxmonitor@mozilla.org\":{\"version\":\"2.8\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"c3fa0876-0fe4-40af-b690-0ecabbe6bb47\",\"screenshots@mozilla.org\":\"d5c643ca-2bef-4f68-bf7a-f43c65fef523\",\"webcompat-reporter@mozilla.org\":\"4187edac-65cb-4245-9446-5b64bb29d07b\",\"webcompat@mozilla.org\":\"ff7db953-503c-4eb1-baeb-28006efee05c\",\"fxmonitor@mozilla.org\":\"f68191ef-5430-4ca5-9f9a-d63587ebcab6\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1547300088);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20181209160329");
user_pref("media.gmp-manager.lastCheck", 1547300087);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 100842);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "1ebccc83-84f7-4de9-b278-56f979bfbdfd");
user_pref("security.sandbox.plugin.tempDirSuffix", "3016dedc-dc60-4a37-8f24-ab297c849503");
user_pref("services.blocklist.addons.checked", 1547300506);
user_pref("services.blocklist.gfx.checked", 1547300506);
user_pref("services.blocklist.onecrl.checked", 1547300506);
user_pref("services.blocklist.pinning.checked", 1547300506);
user_pref("services.blocklist.plugins.checked", 1547300506);
user_pref("services.settings.clock_skew_seconds", -154);
user_pref("services.settings.last_etag", "\"1547206877909\"");
user_pref("services.settings.last_update_seconds", 1547300506);
user_pref("services.settings.main.language-dictionaries.last_check", 1547300506);
user_pref("services.settings.main.onboarding.last_check", 1547300506);
user_pref("services.settings.main.sites-classification.last_check", 1547300506);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1547300201);
user_pref("toolkit.telemetry.cachedClientID", "b43ca095-8cd0-4b93-9f50-27d0860f36ac");
user_pref("toolkit.telemetry.previousBuildID", "20181209160329");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
